# compose.yaml
services:
  mercure:
    image: dunglas/mercure
    environment:
      SERVER_NAME: ':8002'
      MERCURE_PUBLISHER_JWT_KEY: "512caae005bf589fb4d7728301205db273d55aa5030a2ab6e2acb2955063b6f1"
      MERCURE_SUBSCRIBER_JWT_KEY: "56500e38ddc0360f0525d7545ba708d1b873aedcc2c5caca1c8077f398b2d409"
    ports:
      - "8002:8002"
      - "80:80"
      - "443:443"
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config:
